//用于通信的
role_data={
	'001':{
		'name':'唐如',//名字
		'type':'001',//类型
		'lv':0,//等级
		'avatar':'images/role/ava/ava_001.png',//头像
		'model':'images/role/model/001_normal.png',//裸模
		'health':1000,//生命
		'exp_current':12345,//当前经验值
		'exp_next':20000,//升级经验值
		'attack':15,//攻击
		'defend':3,//防御
		'crit':5,//暴击
		'miss':5,//闪避
		'weapon':'001',//武器编号
		'clothes':'001',//衣服编号
		'skill_point':'2',
		'skill_list':['001','2','002','2','003','2']
	},
	'002':{
		'name':'祝离',//名字
		'type':'002',//类型
		'lv':0,//等级
		'avatar':'images/role/ava/ava_001.png',//头像
		'model':'images/role/model/001_normal.png',//裸模
		'health':1000,//生命
		'exp_current':12345,//当前经验值
		'exp_next':20000,//升级经验值
		'attack':15,//攻击
		'defend':3,//防御
		'crit':5,//暴击
		'miss':5,//闪避
		'weapon':'001',//武器编号
		'clothes':'001',//衣服编号
		//技能部待讨论
		'skill_point':'2',
		'skill_list':['001','2','002','2','003','2']
	},
	'003':{
		'name':'碧青',//名字
		'lv':0,//等级
		'avatar':'images/role/ava/ava_001.png',//头像
		'model':'images/role/model/001_normal.png',//裸模
		'health':1000,//生命
		'exp_current':12345,//当前经验值
		'exp_next':20000,//升级经验值
		'attack':15,//攻击
		'defend':3,//防御
		'crit':5,//暴击
		'miss':5,//闪避
		'weapon':'001',//武器编号
		'clothes':'001',//衣服编号
		'skill_point':'2',
		'skill_list':['001','2','002','2','003','2']
	},
}

item_data={
		'weapon':{
			'001':{
				'name':'秃毛笔',//名称
				'description':'路边最普通不过的十文钱一支的毛笔。',//描述
				'icon':'images/weapon/icons/001.png',//图标路径
				'model':'images/weapon/model/001.png',//模型路径
				'health_addition':0,//血量加成
				'attack_addition':10,//攻击加成
				'defend_addition':3,//防御加成
				'crit_addition':0,//暴击加成
				'for':'001',//适用角色（读取role_data中的数据）
				'open':true//是否已经获得
			},
			'002':{
				'name':'羊毫笔',//名称
				'description':'羊毫制成的毛笔，柔而无锋，书而无骨，不为书法家们喜爱，故而价格廉宜。',
				'icon':'images/weapon/icons/001.png',
				'model':'images/weapon/model/001.png',
				'health_addition':0,
				'attack_addition':10,
				'defend_addition':3,
				'crit_addition':0,
				'for':'001',
				'open':false
			},
			'003':{
				'name':'长剑',
				'description':'“长剑一杯酒， 男儿方寸心。”游侠儿的必备装饰，看起来很拉风的样子。',
				'icon':'images/weapon/icons/001.png',
				'model':'images/weapon/model/001.png',
				'health_addition':0,
				'attack_addition':10,
				'defend_addition':3,
				'crit_addition':0,
				'for':'002',
				'open':false
			},
			'004':{
				'name':'青铜剑',
				'description':'古法锻冶的剑，拿在手里颇有分量，比普通的长剑看起来有内涵的样子，是这几年的流行选择。',
				'icon':'images/weapon/icons/001.png',
				'model':'images/weapon/model/001.png',
				'health_addition':0,
				'attack_addition':10,
				'defend_addition':3,
				'crit_addition':0,
				'for':'002',
				'open':false	
			},
			'005':{
				'name':'晶球',
				'description':'白水晶磨制的透明圆球，看不出有什么特别。',
				'icon':'images/weapon/icons/001.png',
				'model':'images/weapon/model/001.png',
				'health_addition':0,
				'attack_addition':10,
				'defend_addition':3,
				'crit_addition':0,
				'for':'002',
				'open':false	
			},
			'006':{
				'name':'紫晶珠',
				'description':'紫光流转的珠子，煞是好看，据说具有神秘的力量。',
				'icon':'images/weapon/icons/001.png',
				'model':'images/weapon/model/001.png',
				'health_addition':0,
				'attack_addition':10,
				'defend_addition':3,
				'crit_addition':0,
				'for':'002',
				'open':false	
			},
			'007':{
				'name':'十八妹',
				'description':'虽然外表看起来像是一把菜刀，但是其主人坚称它是一柄剑，能够增加一定程度的攻击和防御。',
				'icon':'images/weapon/icons/001.png',
				'model':'images/weapon/model/001.png',
				'health_addition':0,
				'attack_addition':10,
				'defend_addition':3,
				'crit_addition':0,
				'for':'002',
				'open':false	
			}
		},

		'clothes':{
			'001':{
				'name':'粗布衣',
				'description':'旧衣店出售的破旧衣服，上面还打了几个补丁。',
				'icon':'images/weapon/icons/001.png',
				'model':'images/weapon/model/001.png',
				'health_addition':0,
				'attack_addition':10,
				'defend_addition':3,
				'crit_addition':0,
				'speed_addition':0, 
				'for':'001',//适用角色
				'open':true
			},
			'002':{
				'name':'棉布衣',
				'description':'一般穷书生穿的布袍，只是单纯的布袍而已。',
				'icon':'images/weapon/icons/001.png',
				'model':'images/weapon/model/001.png',
				'health_addition':0,
				'attack_addition':10,
				'defend_addition':3,
				'crit_addition':0,
				'speed_addition':0, 
				'for':'001',
				'open':false
			},
			'003':{
				'name':'锦袍',
				'description':'富家公子常穿的便服，冬暖夏凉。',
				'icon':'images/weapon/icons/001.png',
				'model':'images/weapon/model/001.png',
				'health_addition':0,
				'attack_addition':10,
				'defend_addition':3,
				'crit_addition':0,
				'speed_addition':0, 
				'for':'002',//适用角色
				'open':true
			},
			'004':{
				'name':'蜀锦袍',
				'description':'“犹馀蜀中锦，爱惜比甘棠。”蜀地的锦缎千载驰名，用其制作的袍子自然也价格不菲。',
				'icon':'images/weapon/icons/001.png',
				'model':'images/weapon/model/001.png',
				'health_addition':0,
				'attack_addition':10,
				'defend_addition':3,
				'crit_addition':0,
				'speed_addition':0, 
				'for':'002',//适用角色
				'open':false
			},
			'005':{
				'name':'麟裳',
				'description':'人鱼国最常见的平民装束。',
				'icon':'images/weapon/icons/001.png',
				'model':'images/weapon/model/001.png',
				'health_addition':0,
				'attack_addition':10,
				'defend_addition':3,
				'crit_addition':0,
				'speed_addition':0, 
				'for':'003',//适用角色
				'open':true
			},
			'006':{
				'name':'华彩裙',
				'description':'少女们钟爱的薄绸裙，在阳光下会隐隐泛出五色华彩。',
				'icon':'images/weapon/icons/001.png',
				'model':'images/weapon/model/001.png',
				'health_addition':0,
				'attack_addition':10,
				'defend_addition':3,
				'crit_addition':0,
				'speed_addition':0, 
				'for':'003',//适用角色
				'open':false
			}
		}
}

//技能：
skill_data={
	'001':{
		'name':'枯木逢春',
		'description':'',
		'type':'',
		'icon':'',
		'level_limit':['0','1','2','3'],
		'cd':3,
		'data':{
			'blood_addition':'',
		}
	},
	'002':{}
}

console.log(skill_data['001']['name']);
