//用于初始化人物的数据
woh.role_init_data={
	'001':{
		'name':'唐如',//名字
		'type':'001',//类型
		'lv':0,//等级(根据类型和等级读取其他数据)
		'avatar':'images/role/ava/ava_001.png',//头像
		'exp_current':0,//当前经验值
		'weapon':'001',//武器编号
		'clothes':'001',//衣服编号
		'skill_point':'0',//剩余技能点
		'skill_list':{
			'疾风刺':0, 
			'落英旋':0,
			'浮云风卷':0,
			'醉舞秋红':0
		}//技能列表（编号-等级）
	},
	'002':{
		'name':'程少非',//名字
		'type':'002',//类型
		'lv':2,//等级
		'avatar':'images/role/ava/ava_001.png',//头像
		'exp_current':1300,//当前经验值
		'weapon':'003',//武器编号
		'clothes':'003',//衣服编号
		'skill_point':'0',
		'skill_list':{
			'灵焰灼':1,
			'心月斩':1,
			'天狐之怒':0,
			'心宿炎障':0,
		}
	},
	'003':{
		'name':'碧青',//名字
		'type':'003',//类型
		'lv':2,//等级
		'avatar':'images/role/ava/ava_001.png',//头像
		'exp_current':1300,//当前经验值
		'weapon':'005',//武器编号
		'clothes':'005',//衣服编号
		'skill_point':0,
		'skill_list':{
			'花雨露':1,
			'水月霖':1,
			'芳华流转':0,
			'镜泉润物':0
		}
	},
}

woh.item_data={
		'weapon':{
			'001':{
				'name':'圆月刀',//名称
				'description':'常见的小刀,可以用来切切水果什么的。',//描述
				'icon':'images/weapon/icons/001.png',//图标路径
				'model':'images/weapon/model/001.png',//模型路径
				'health_addition':0,//血量加成
				'attack_addition':3,//攻击加成
				'defend_addition':0,//防御加成
				'crit_addition':0,//暴击加成
				'for':'001',//适用角色（读取role_data中的数据）
				'open':true//是否已经获得
			},
			'002':{
				'name':'匕首',//名称
				'description':'勉强能够用来防身的便宜货,居家旅行常备的防盗工具',
				'icon':'images/weapon/icons/001.png',
				'model':'images/weapon/model/001.png',
				'health_addition':0,
				'attack_addition':10,
				'defend_addition':3,
				'crit_addition':0,
				'for':'001',
				'open':false
			},
			'003':{
				'name':'长剑',
				'description':'“长剑一杯酒, 男儿方寸心。”游侠儿的必备装饰,看起来很拉风的样子。',
				'icon':'images/weapon/icons/001.png',
				'model':'images/weapon/model/001.png',
				'health_addition':0,
				'attack_addition':10,
				'defend_addition':3,
				'crit_addition':0,
				'for':'002',
				'open':false
			},
			'004':{
				'name':'青铜剑',
				'description':'古法锻冶的剑,拿在手里颇有分量,比普通的长剑看起来有内涵的样子,是这几年的流行选择。',
				'icon':'images/weapon/icons/001.png',
				'model':'images/weapon/model/001.png',
				'health_addition':0,
				'attack_addition':10,
				'defend_addition':3,
				'crit_addition':0,
				'for':'002',
				'open':false	
			},
			'005':{
				'name':'晶球',
				'description':'白水晶磨制的透明圆球,看不出有什么特别。',
				'icon':'images/weapon/icons/001.png',
				'model':'images/weapon/model/001.png',
				'health_addition':0,
				'attack_addition':10,
				'defend_addition':3,
				'crit_addition':0,
				'for':'002',
				'open':false	
			},
			'006':{
				'name':'紫晶珠',
				'description':'紫光流转的珠子,煞是好看,据说具有神秘的力量。',
				'icon':'images/weapon/icons/001.png',
				'model':'images/weapon/model/001.png',
				'health_addition':0,
				'attack_addition':10,
				'defend_addition':3,
				'crit_addition':0,
				'for':'003',
				'open':false	
			},
			'007':{
				'name':'十八妹',
				'description':'虽然外表看起来像是一把菜刀,但是其主人坚称它是一柄剑,能够增加一定程度的攻击和防御。',
				'icon':'images/weapon/icons/001.png',
				'model':'images/weapon/model/001.png',
				'health_addition':0,
				'attack_addition':10,
				'defend_addition':3,
				'crit_addition':0,
				'for':'003',
				'open':false	
			}
		},

		'clothes':{
			'001':{
				'name':'粗布衣',
				'description':'旧衣店出售的破旧衣服,上面还打了几个补丁。',
				'icon':'images/weapon/icons/001.png',
				'model':'images/weapon/model/001.png',
				'health_addition':0,
				'attack_addition':10,
				'defend_addition':3,
				'crit_addition':0,
				'speed_addition':0, 
				'for':'001',//适用角色
				'open':true
			},
			'002':{
				'name':'棉布衣',
				'description':'一般穷书生穿的布袍,只是单纯的布袍而已。',
				'icon':'images/weapon/icons/001.png',
				'model':'images/weapon/model/001.png',
				'health_addition':0,
				'attack_addition':10,
				'defend_addition':3,
				'crit_addition':0,
				'speed_addition':0, 
				'for':'001',
				'open':false
			},
			'003':{
				'name':'锦袍',
				'description':'富家公子常穿的便服,冬暖夏凉。',
				'icon':'images/weapon/icons/001.png',
				'model':'images/weapon/model/001.png',
				'health_addition':0,
				'attack_addition':10,
				'defend_addition':3,
				'crit_addition':0,
				'speed_addition':0, 
				'for':'002',//适用角色
				'open':true
			},
			'004':{
				'name':'蜀锦袍',
				'description':'“犹馀蜀中锦,爱惜比甘棠。”蜀地的锦缎千载驰名,用其制作的袍子自然也价格不菲。',
				'icon':'images/weapon/icons/001.png',
				'model':'images/weapon/model/001.png',
				'health_addition':0,
				'attack_addition':10,
				'defend_addition':3,
				'crit_addition':0,
				'speed_addition':0, 
				'for':'002',//适用角色
				'open':false
			},
			'005':{
				'name':'麟裳',
				'description':'人鱼国最常见的平民装束。',
				'icon':'images/weapon/icons/001.png',
				'model':'images/weapon/model/001.png',
				'health_addition':0,
				'attack_addition':10,
				'defend_addition':3,
				'crit_addition':0,
				'speed_addition':0, 
				'for':'003',//适用角色
				'open':true
			},
			'006':{
				'name':'华彩裙',
				'description':'少女们钟爱的薄绸裙,在阳光下会隐隐泛出五色华彩。',
				'icon':'images/weapon/icons/001.png',
				'model':'images/weapon/model/001.png',
				'health_addition':0,
				'attack_addition':10,
				'defend_addition':3,
				'crit_addition':0,
				'speed_addition':0, 
				'for':'003',//适用角色
				'open':false
			}
		}
}

//技能影响
//直接伤害,回复生命,区域伤害,添加buff
//buff类型：速度类（加减）,防御类（加减）,暴击类（加减）,生命类（加减）
//注：大招均为手势识别施放,每个人的第四个招为大招

//目前唐如的三个技能分别为 单体攻击 瞬发群体攻击 吟唱群体攻击 大招为全屏幕地图炮高伤害攻击 

woh.skill_data={
	'疾风刺':{
		'description':'追求一击必杀的招式,轻灵迅捷,其威力在不同修为者手中截然不同。（冲向对方进行一次攻击）',//技能描述
		'icon':'resources/iamges/001.png',//技能图标路径
		'level_limit':[1,2,4,5,7],//每一阶段的可点等级
		'cd':15,//CD时间
		
		//技能影响
		'data':{
			//单体直接伤害，攻击范围等同于武器攻击范围
			'attack_direct':{
				'target':'enemySingle',//使用对象 selfSingle/ememySingle/selfRange/ememyRange/selfAll/enemyAll
				'attack_addition':[10,12,14,16,18],//伤害增加值,对应不同等级
		    }
		}
	},
	'落英染':{
		'description':'英华翩舞兮,染景纷纷旧年时。美好的追忆总能治愈人心。（己方全体生命回复）',//技能描述
		'icon':'resources/iamges/001.png',//技能图标路径
		'level_limit':[2,3,4,8,10],//每一阶段的可点等级
		'cd':15,//CD时间
		//技能影响
		'data':{
		    //回复
		    'recover':{
		    	'target':'selfAll',
		    	'attack_addition':[]
		    },
		}
	},
	'浮云风卷':{
		'description':'飘风自南,泱泱涤尘。凝神静气,荡净浮埃。（以施法者为中心,在半径200的区域内进行群体攻击）',//技能描述
		'icon':'resources/iamges/001.png',//技能图标路径
		'level_limit':[2,3,4,9,11],//每一阶段的可点等级
		'cd':30,//CD时间
		//技能影响
		'data':{
			//单体直接伤害
			'attack_direct':{

		    },
		    //回复
		    'recover':{

		    },
		    //区域伤害
		    'attack_area':{
		    	'target':'enemyRange',//使用对象 selfSingle/ememySingle/selfRange/ememyRange
				'duration':3,//动作持续时间
				'continue':3,//技能有效时间
				'times':3,//造成的伤害次数
				'range':200, //技能的攻击范围,数值表示攻击范围的半径
				'attack_addition':[50,60,70,80,90],//伤害增加值
		    },
		    //添加buff
		    'buff':{

		    }
		}
	},
	'醉舞秋红':{
		'description':'日暮秋烟起,萧萧枫树林。寄托壮志未酬哀思的招式,饱含尽除敌寇的怨愤。(敌方全体造成大量伤害)',
		'icon':'resources/iamges/001.png',//技能图标路径
		'level_limit':[5,8,9,13,15],//每一阶段的可点等级
		'cd':120,//CD时间
		//技能影响
		'data':{
		    //区域伤害
		    'attack_area':{
		    	'target':'enemyAll',//使用对象 selfSingle/ememySingle/selfRange/ememyRange
				'duration':0.5,//动作持续时间
				'continue':5,//技能效果持续时间
				'attack_addition':30,//伤害增加值
		    },
		    //添加buff
		    //'buff':{

		    //}
		}
	},
	'灵焰灼':{
		'description':'星星之火,可以燎原,一旦燃起,便势不可当。(受到攻击的敌人每秒受到伤害,持续五秒)',
		'icon':'resources/iamges/001.png',//技能图标路径
		'level_limit':[1,2,4,5,7],//每一阶段的可点等级
		'cd':15,//CD时间
		//技能影响
		'data':{
			
		    //添加buff
		    'buff':{
		    	'target':'enemyRange',
		    	'health_addition':[-20,-30,-40,-50,-60],
		    	'duration':5,
		    	'times':5
		    }
		}
	},
	'心月斩':{
		'description':'心月狐,其性属火,喜好游戏人间,祸乱人心。（造成范围伤害,受到伤害者行动封印。）',
		'icon':'resources/iamges/001.png',//技能图标路径
		'level_limit':[2,3,4,8,10],//每一阶段的可点等级
		'cd':15,//CD时间
		//技能影响
		'data':{
		    'attack_area':{
		    	'target':'enemyRange',//使用对象 selfSingle/ememySingle/selfRange/ememyRange
				'range':10,
				'attack_addition':[10,20,30,40,50],//伤害增加值
		    },
		    //添加buff
		    'buff':{
		    	'target':'enemyRange',
		    	'speed_addition':-9999,
		    	'duration':[0.5,1,1.2,1.5,2]
		    }
		}
	},
	'天狐之怒':{
		'description':'“青丘之山,有兽焉,其状如狐而九尾。”九尾狐出,乃世间将有大乱之象。（全部敌人受到连续伤害）',
		'icon':'resources/iamges/001.png',//技能图标路径
		'level_limit':[2,3,4,9,11],//每一阶段的可点等级
		'cd':30,//CD时间
		//技能影响
		'data':{
		    'attack_area':{
		    	
		    },
		    //添加buff
		    'buff':{
		    	
		    }
		}
	},
	'心宿炎障':{
		'description':'心宿,又称大火,东方苍龙七宿之心,守心护元,灭障除魔。（全部队友获得5秒免伤状态）',
		'icon':'resources/iamges/001.png',//技能图标路径
		'level_limit':[5,8,9,13,15],//每一阶段的可点等级
		'cd':60,//CD时间
		//技能影响
		'data':{
		    'attack_area':{
		    	
		    },
		    //添加buff
		    'buff':{
		    	
		    }
		}
	},
	'花雨露':{
		'description':'花雨润泽,沁人心脾,沐浴者神清气爽。（单体回复体力）',
		'icon':'resources/iamges/001.png',//技能图标路径
		'level_limit':[5,6,7,8,9],//每一阶段的可点等级
		'cd':3,//CD时间
		//技能影响
		'data':{
		    
		}
	},
	'水月霖':{
		'description':'水月之力属幻,堕入幽梦者,如履太虚。（敌方全体进入减速状态）',
		'icon':'resources/iamges/001.png',//技能图标路径
		'level_limit':[5,6,7,8,9],//每一阶段的可点等级
		'cd':3,//CD时间
		//技能影响
		'data':{
		    
		}
	},
	'芳华流转':{
		'description':'芳华轻笑,千红流转,生机盎然。（全体回复体力）',
		'icon':'resources/iamges/001.png',//技能图标路径
		'level_limit':[5,6,7,8,9],//每一阶段的可点等级
		'cd':3,//CD时间
		//技能影响
	},
	'镜泉润物':{
		'description':'泉之始,镜之初,润泽万物,生生不息。（全体回复大量体力并解除一切负面状态）',
		'icon':'resources/iamges/001.png',//技能图标路径
		'level_limit':[5,6,7,8,9],//每一阶段的可点等级
		'cd':3,//CD时间
		//技能影响
	}
}

//怪物初始化数据
woh.monster_init_data={
	'crab':{
		'health':140,
		'attack':20,
	},
	'crab_boss':{
		'health':1400,
		'attack':30,
	}

}
//console.log(role_data);
