//用于通信的
role_data={
	'001':{
		'name':'唐如',//名字
		'type':'001',//类型
		'lv':0,//等级
		'avatar':'images/role/ava/ava_001.png',//头像
		'model':'images/role/model/001_normal.png',//裸模
		'health':1000,//生命
		'exp_current':12345,//当前经验值
		'exp_next':20000,//升级经验值
		'attack':15,//攻击
		'defend':3,//防御
		'crit':5,//暴击
		'miss':5,//闪避
		'weapon':'001',//武器编号
		'clothes':'001',//衣服编号
		'skill_point':'2',//剩余技能点
		'skill_list':['001',2,'002',2,'003',1,'004',0]//技能列表（编号-等级）
	},
	'002':{
		'name':'祝离',//名字
		'type':'002',//类型
		'lv':0,//等级
		'avatar':'images/role/ava/ava_001.png',//头像
		'model':'images/role/model/001_normal.png',//裸模
		'health':1000,//生命
		'exp_current':12345,//当前经验值
		'exp_next':20000,//升级经验值
		'attack':15,//攻击
		'defend':3,//防御
		'crit':5,//暴击
		'miss':5,//闪避
		'weapon':'001',//武器编号
		'clothes':'001',//衣服编号
		//技能部待讨论
		'skill_point':'2',
		'skill_list':['005',2,'006',2,'007',1,'008',0]
	},
	'003':{
		'name':'碧青',//名字
		'type':'003',//类型
		'lv':0,//等级
		'avatar':'images/role/ava/ava_001.png',//头像
		'model':'images/role/model/001_normal.png',//裸模
		'health':1000,//生命
		'exp_current':12345,//当前经验值
		'exp_next':20000,//升级经验值
		'attack':15,//攻击
		'defend':3,//防御
		'crit':5,//暴击
		'miss':5,//闪避
		'weapon':'001',//武器编号
		'clothes':'001',//衣服编号
		'skill_point':'2',
		'skill_list':['009',2,'010',2,'011',1,'012',0]
	},
}

item_data={
		'weapon':{
			'001':{
				'name':'小刀',//名称
				'description':'常见的小刀，可以用来切切水果什么的。',//描述
				'icon':'images/weapon/icons/001.png',//图标路径
				'model':'images/weapon/model/001.png',//模型路径
				'health_addition':0,//血量加成
				'attack_addition':3,//攻击加成
				'defend_addition':0,//防御加成
				'crit_addition':0,//暴击加成
				'for':'001',//适用角色（读取role_data中的数据）
				'open':true//是否已经获得
			},
			'002':{
				'name':'匕首',//名称
				'description':'勉强能够用来防身的便宜货，居家旅行常备的防盗工具',
				'icon':'images/weapon/icons/001.png',
				'model':'images/weapon/model/001.png',
				'health_addition':0,
				'attack_addition':10,
				'defend_addition':3,
				'crit_addition':0,
				'for':'001',
				'open':false
			},
			'003':{
				'name':'长剑',
				'description':'“长剑一杯酒， 男儿方寸心。”游侠儿的必备装饰，看起来很拉风的样子。',
				'icon':'images/weapon/icons/001.png',
				'model':'images/weapon/model/001.png',
				'health_addition':0,
				'attack_addition':10,
				'defend_addition':3,
				'crit_addition':0,
				'for':'002',
				'open':false
			},
			'004':{
				'name':'青铜剑',
				'description':'古法锻冶的剑，拿在手里颇有分量，比普通的长剑看起来有内涵的样子，是这几年的流行选择。',
				'icon':'images/weapon/icons/001.png',
				'model':'images/weapon/model/001.png',
				'health_addition':0,
				'attack_addition':10,
				'defend_addition':3,
				'crit_addition':0,
				'for':'002',
				'open':false	
			},
			'005':{
				'name':'晶球',
				'description':'白水晶磨制的透明圆球，看不出有什么特别。',
				'icon':'images/weapon/icons/001.png',
				'model':'images/weapon/model/001.png',
				'health_addition':0,
				'attack_addition':10,
				'defend_addition':3,
				'crit_addition':0,
				'for':'002',
				'open':false	
			},
			'006':{
				'name':'紫晶珠',
				'description':'紫光流转的珠子，煞是好看，据说具有神秘的力量。',
				'icon':'images/weapon/icons/001.png',
				'model':'images/weapon/model/001.png',
				'health_addition':0,
				'attack_addition':10,
				'defend_addition':3,
				'crit_addition':0,
				'for':'003',
				'open':false	
			},
			'007':{
				'name':'十八妹',
				'description':'虽然外表看起来像是一把菜刀，但是其主人坚称它是一柄剑，能够增加一定程度的攻击和防御。',
				'icon':'images/weapon/icons/001.png',
				'model':'images/weapon/model/001.png',
				'health_addition':0,
				'attack_addition':10,
				'defend_addition':3,
				'crit_addition':0,
				'for':'003',
				'open':false	
			}
		},

		'clothes':{
			'001':{
				'name':'粗布衣',
				'description':'旧衣店出售的破旧衣服，上面还打了几个补丁。',
				'icon':'images/weapon/icons/001.png',
				'model':'images/weapon/model/001.png',
				'health_addition':0,
				'attack_addition':10,
				'defend_addition':3,
				'crit_addition':0,
				'speed_addition':0, 
				'for':'001',//适用角色
				'open':true
			},
			'002':{
				'name':'棉布衣',
				'description':'一般穷书生穿的布袍，只是单纯的布袍而已。',
				'icon':'images/weapon/icons/001.png',
				'model':'images/weapon/model/001.png',
				'health_addition':0,
				'attack_addition':10,
				'defend_addition':3,
				'crit_addition':0,
				'speed_addition':0, 
				'for':'001',
				'open':false
			},
			'003':{
				'name':'锦袍',
				'description':'富家公子常穿的便服，冬暖夏凉。',
				'icon':'images/weapon/icons/001.png',
				'model':'images/weapon/model/001.png',
				'health_addition':0,
				'attack_addition':10,
				'defend_addition':3,
				'crit_addition':0,
				'speed_addition':0, 
				'for':'002',//适用角色
				'open':true
			},
			'004':{
				'name':'蜀锦袍',
				'description':'“犹馀蜀中锦，爱惜比甘棠。”蜀地的锦缎千载驰名，用其制作的袍子自然也价格不菲。',
				'icon':'images/weapon/icons/001.png',
				'model':'images/weapon/model/001.png',
				'health_addition':0,
				'attack_addition':10,
				'defend_addition':3,
				'crit_addition':0,
				'speed_addition':0, 
				'for':'002',//适用角色
				'open':false
			},
			'005':{
				'name':'麟裳',
				'description':'人鱼国最常见的平民装束。',
				'icon':'images/weapon/icons/001.png',
				'model':'images/weapon/model/001.png',
				'health_addition':0,
				'attack_addition':10,
				'defend_addition':3,
				'crit_addition':0,
				'speed_addition':0, 
				'for':'003',//适用角色
				'open':true
			},
			'006':{
				'name':'华彩裙',
				'description':'少女们钟爱的薄绸裙，在阳光下会隐隐泛出五色华彩。',
				'icon':'images/weapon/icons/001.png',
				'model':'images/weapon/model/001.png',
				'health_addition':0,
				'attack_addition':10,
				'defend_addition':3,
				'crit_addition':0,
				'speed_addition':0, 
				'for':'003',//适用角色
				'open':false
			}
		}
}

//技能基础类型 以001-006标识
//攻击技能 直接对敌方产生伤害
//诅咒技能 一段时间内持续对敌方产生伤害
//强控制技能 一段时间内让敌方无法行动 
//弱控制技能 一段时间内让敌方无法攻击、减速
//增益类技能 一定时间内对方产生增益
//治疗类技能 增加己方的血量


skill_data={
	'001':{
		'name':'流风',//技能
		'description':'追求一击必杀的招式，冲向对方进行一次攻击。伤害增加40。',//技能描述
		'type':'001',//技能类型
		'target':'enemy',//使用对象 self/ememy
		'range':0, //技能的攻击范围，数值表示攻击范围的半径，0表示单体近身攻击
		'icon':'resources/iamges/001.png',//技能图标路径
		'level_limit':[0,3,4,5,7],//每一阶段的可点等级
		'cd':3,//CD时间
		'duration':0.5,//动作持续时间
		'continue':0,//技能效果持续时间
		'lock':false;//技能是否可以被打断
		'data':{
			'attack_addition':40,
			'target_count':'single'
		}
	},
	'002':{

	}
}

console.log(role_data);
